# -*- coding: utf-8 -*-
"""ExtendedEuclid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zakhrH9vuVmWdD7TAr7ZQuZBIVkQL8kl
"""

def my_euclid(a,b):
  """Uses extended euclidean algorithm to find integer solutions to 
  ax + by = gcd(x,y)"""
  # Base case
  if a == 0 and b != 0:
    return b, 0, 1
  # Recursive step
  else:
    d, x, y = my_euclid(b % a, a)
    return d, y - (b//a) * x, x